import bcrypt from 'bcryptjs';
import { randomUUID } from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { calculateDistanceKm, findNearestIndianCity } from './indianCities.js';

export { calculateDistanceKm, findNearestIndianCity };

const DATA_DIR = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../data');
const DATA_FILE = path.join(DATA_DIR, 'revora_db.json');

export const db = {
  users: [],
  stores: [],
  ratings: [],
};

export const saveDbToFile = () => {
  try {
    if (!fs.existsSync(DATA_DIR)) {
      fs.mkdirSync(DATA_DIR, { recursive: true });
    }
    fs.writeFileSync(DATA_FILE, JSON.stringify(db, null, 2), 'utf-8');
  } catch (err) {
    console.warn('Failed to save revora_db:', err.message);
  }
};

export const loadDbFromFile = () => {
  try {
    if (fs.existsSync(DATA_FILE)) {
      const content = fs.readFileSync(DATA_FILE, 'utf-8');
      const loaded = JSON.parse(content);
      if (Array.isArray(loaded.users) && Array.isArray(loaded.stores) && Array.isArray(loaded.ratings)) {
        db.users = loaded.users;
        db.stores = loaded.stores;
        db.ratings = loaded.ratings;
        return true;
      }
    }
  } catch (err) {
    console.warn('Failed to load revora_db:', err.message);
  }
  return false;
};

const now = (daysAgo = 0) => new Date(Date.now() - daysAgo * 86400000).toISOString();
const passwordHash = (password) => bcrypt.hashSync(password, 10);

export const makeId = (prefix) => `${prefix}_${randomUUID().slice(0, 12)}`;

export const resetData = (force = false) => {
  if (!force && loadDbFromFile()) {
    return;
  }
  db.users = [
    {
      id: 'usr_admin_001',
      name: 'Avery Sterling',
      email: 'admin@revora.app',
      passwordHash: passwordHash('Admin!234'),
      address: '14 Observatory Way, Fort, Mumbai',
      city: 'Mumbai',
      lat: 18.9300,
      lng: 72.8330,
      role: 'ADMIN',
      createdAt: now(120),
      updatedAt: now(2),
    },
    {
      id: 'usr_owner_001',
      name: 'Mara Ellison',
      email: 'owner@revora.app',
      passwordHash: passwordHash('Owner!234'),
      address: 'Chapel Road, Bandra West, Mumbai',
      city: 'Mumbai',
      lat: 19.0550,
      lng: 72.8290,
      role: 'STORE_OWNER',
      createdAt: now(90),
      updatedAt: now(5),
    },
    {
      id: 'usr_owner_002',
      name: 'Jon Bellweather',
      email: 'jon@revora.app',
      passwordHash: passwordHash('Owner!234'),
      address: '100ft Road, Indiranagar, Bengaluru',
      city: 'Bengaluru',
      lat: 12.9780,
      lng: 77.6400,
      role: 'STORE_OWNER',
      createdAt: now(86),
      updatedAt: now(4),
    },
    {
      id: 'usr_user_001',
      name: 'Nora Alvarez',
      email: 'nora@revora.app',
      passwordHash: passwordHash('User!2345'),
      address: 'Arera Colony, Bhopal',
      city: 'Bhopal',
      lat: 23.2145,
      lng: 77.4320,
      role: 'USER',
      createdAt: now(40),
      updatedAt: now(10),
    },
    {
      id: 'usr_user_002',
      name: 'Theo Whitman',
      email: 'theo@revora.app',
      passwordHash: passwordHash('User!2345'),
      address: 'Lodhi Colony, New Delhi',
      city: 'Delhi',
      lat: 28.5890,
      lng: 77.2250,
      role: 'USER',
      createdAt: now(32),
      updatedAt: now(8),
    },
    {
      id: 'usr_user_003',
      name: 'Priya Nanduri',
      email: 'priya@revora.app',
      passwordHash: passwordHash('User!2345'),
      address: 'Koramangala 4th Block, Bengaluru',
      city: 'Bengaluru',
      lat: 12.9350,
      lng: 77.6250,
      role: 'USER',
      createdAt: now(25),
      updatedAt: now(7),
    },
  ];

  db.stores = [
    // --- BHOPAL Cafes & Restaurants (Madhya Pradesh) ---
    {
      id: 'store_bho_001',
      name: 'Under The Mango Tree (Jehan Numa Palace)',
      email: 'reservations@jehannuma.com',
      address: 'Jehan Numa Palace, 157 Shamla Hills, Bhopal',
      city: 'Bhopal',
      country: 'IN',
      category: 'Heritage Fine Dining & North Indian',
      tags: ['Heritage', 'Fine Dining', 'North Indian', 'Romantic', 'Restaurant'],
      lat: 23.2428,
      lng: 77.3872,
      ownerId: null,
      createdAt: now(105),
      updatedAt: now(2),
    },
    {
      id: 'store_bho_002',
      name: 'The Bhopal Bakehouse & Cafe',
      email: 'arera@bhopalbakehouse.in',
      address: 'E-3/45, 10 No. Stop, Arera Colony, Bhopal',
      city: 'Bhopal',
      country: 'IN',
      category: 'Artisan Cafe & Craft Bakery',
      tags: ['Cafe', 'Bakery', 'Specialty Coffee', 'Sourdough', 'Desserts'],
      lat: 23.2145,
      lng: 77.4320,
      ownerId: 'usr_owner_001',
      createdAt: now(100),
      updatedAt: now(3),
    },
    {
      id: 'store_bho_003',
      name: 'Mocha Cafe & Bar',
      email: 'bhopal@mochacafe.in',
      address: 'Near 10 No. Market, E-4, Arera Colony, Bhopal',
      city: 'Bhopal',
      country: 'IN',
      category: 'Contemporary Cafe & Continental',
      tags: ['Cafe', 'Continental', 'Coffee', 'Desserts', 'Brunch'],
      lat: 23.2120,
      lng: 77.4305,
      ownerId: null,
      createdAt: now(95),
      updatedAt: now(4),
    },
    {
      id: 'store_bho_004',
      name: 'Indian Coffee House (ICH New Market)',
      email: 'ich.newmarket@bhopal.in',
      address: 'Near Top N Town, Malviya Nagar, New Market, Bhopal',
      city: 'Bhopal',
      country: 'IN',
      category: 'Historic Heritage Coffee House',
      tags: ['Cafe', 'Filter Coffee', 'Heritage', 'South Indian Breakfast'],
      lat: 23.2382,
      lng: 77.4019,
      ownerId: null,
      createdAt: now(120),
      updatedAt: now(1),
    },
    {
      id: 'store_bho_005',
      name: 'Amer Bakery Hut',
      email: 'abh@hotelamerpalace.com',
      address: 'Hotel Amer Palace, Zone-II, MP Nagar, Bhopal',
      city: 'Bhopal',
      country: 'IN',
      category: 'Legendary Bakery & Fast Casual Cafe',
      tags: ['Bakery', 'Cafe', 'Pizzas', 'Cakes & Pastries'],
      lat: 23.2325,
      lng: 77.4352,
      ownerId: null,
      createdAt: now(98),
      updatedAt: now(5),
    },
    {
      id: 'store_bho_006',
      name: 'Wind & Waves Restaurant (MPT)',
      email: 'windandwaves@mptourism.in',
      address: 'Upper Lake Promenade, Shamla Hills, Bhopal',
      city: 'Bhopal',
      country: 'IN',
      category: 'Lakeside View Cafe & Dining',
      tags: ['Restaurant', 'Lake View', 'Coffee & Snacks', 'Sunset Dining'],
      lat: 23.2470,
      lng: 77.3815,
      ownerId: null,
      createdAt: now(92),
      updatedAt: now(2),
    },
    {
      id: 'store_bho_007',
      name: 'Bake-N-Shake',
      email: 'hello@bakenshake.in',
      address: '10 No. Market, Arera Colony, Bhopal',
      city: 'Bhopal',
      country: 'IN',
      category: 'Classic Cafe, Shakes & Bakes',
      tags: ['Cafe', 'Bakery', 'Thick Shakes', 'Pasta & Sandwiches'],
      lat: 23.2132,
      lng: 77.4312,
      ownerId: null,
      createdAt: now(88),
      updatedAt: now(6),
    },
    {
      id: 'store_bho_008',
      name: 'Countryside Bistro & Roastery',
      email: 'gulmohar@countrysidebhopal.com',
      address: 'B-Sector, Gulmohar Colony, Near Shahpura Lake, Bhopal',
      city: 'Bhopal',
      country: 'IN',
      category: 'Specialty Coffee Roastery & Bistro',
      tags: ['Cafe', 'Specialty Coffee', 'Wood-fired Pizza', 'Patio'],
      lat: 23.2005,
      lng: 77.4241,
      ownerId: null,
      createdAt: now(84),
      updatedAt: now(3),
    },
    {
      id: 'store_bho_009',
      name: 'Manohar Dairy & Restaurant',
      email: 'service@manohardairy.com',
      address: '6 Hamidia Road, Near Railway Station & MP Nagar Zone-I, Bhopal',
      city: 'Bhopal',
      country: 'IN',
      category: 'Iconic Dining & Traditional Sweets',
      tags: ['Restaurant', 'Chaat', 'North Indian', 'Sweets & Thali', 'Heritage'],
      lat: 23.2568,
      lng: 77.4102,
      ownerId: null,
      createdAt: now(115),
      updatedAt: now(4),
    },
    {
      id: 'store_bho_010',
      name: 'Shahi Dawat Restaurant',
      email: 'shahidawat@bhopalfood.in',
      address: 'VIP Road, Near Kohefiza Lake View, Bhopal',
      city: 'Bhopal',
      country: 'IN',
      category: 'Traditional Mughlai & Bhopali Cuisine',
      tags: ['Restaurant', 'Mughlai', 'Bhopali Biryani', 'Lake View'],
      lat: 23.2650,
      lng: 77.3910,
      ownerId: null,
      createdAt: now(80),
      updatedAt: now(5),
    },

    // --- INDORE Cafes & Restaurants (Madhya Pradesh) ---
    {
      id: 'store_ind_001',
      name: 'Med Gelato & Bakery Cafe',
      email: 'vijaynagar@medgelato.com',
      address: 'Scheme 54, PU-4, Commercial Area, Vijay Nagar, Indore',
      city: 'Indore',
      country: 'IN',
      category: 'European Gelateria & Artisan Bakery',
      tags: ['Cafe', 'Bakery', 'Artisan Gelato', 'Sourdough'],
      lat: 22.7533,
      lng: 75.8937,
      ownerId: null,
      createdAt: now(90),
      updatedAt: now(3),
    },
    {
      id: 'store_ind_002',
      name: 'Nafees Restaurant',
      email: 'oldpalasia@nafeesrestaurant.com',
      address: 'Apollo Avenue, Old Palasia, Indore',
      city: 'Indore',
      country: 'IN',
      category: 'Famous Mughlai & Biryani Dining',
      tags: ['Restaurant', 'Mughlai', 'Biryani', 'Heritage'],
      lat: 22.7244,
      lng: 75.8839,
      ownerId: null,
      createdAt: now(110),
      updatedAt: now(4),
    },
    {
      id: 'store_ind_003',
      name: 'Cafe Terazza',
      email: 'info@cafeterazza.in',
      address: '10th Floor, Airen Heights, Opposite C21 Mall, Vijay Nagar, Indore',
      city: 'Indore',
      country: 'IN',
      category: 'Rooftop Cafe & Lounge',
      tags: ['Cafe', 'Rooftop', 'Continental', 'Coffee'],
      lat: 22.7488,
      lng: 75.8920,
      ownerId: null,
      createdAt: now(85),
      updatedAt: now(2),
    },

    // --- MUMBAI Cafes & Restaurants ---
    {
      id: 'store_mum_001',
      name: 'Subko Coffee Roasters & Craft Bakehouse',
      email: 'bandra@subko.coffee',
      address: '21A Chapel Road, Ranwar, Bandra West, Mumbai',
      city: 'Mumbai',
      country: 'IN',
      category: 'Specialty Coffee & Bakehouse',
      tags: ['Cafe', 'Specialty Coffee', 'Bakehouse', 'Sourdough'],
      lat: 19.0558,
      lng: 72.8315,
      ownerId: 'usr_owner_001',
      createdAt: now(100),
      updatedAt: now(3),
    },
    {
      id: 'store_mum_002',
      name: 'The Bombay Canteen',
      email: 'table@thebombaycanteen.com',
      address: 'Unit 1, Process House, Kamala Mills, Lower Parel, Mumbai',
      city: 'Mumbai',
      country: 'IN',
      category: 'Modern Regional Restaurant & Bar',
      tags: ['Restaurant', 'Modern Indian', 'Cocktails', 'Dinner'],
      lat: 18.9953,
      lng: 72.8242,
      ownerId: null,
      createdAt: now(95),
      updatedAt: now(4),
    },
    {
      id: 'store_mum_003',
      name: 'Blue Tokai Coffee Roasters (Kala Ghoda)',
      email: 'kalaghoda@bluetokaicoffee.com',
      address: '11/13, Forbes Street, Kala Ghoda, Fort, Mumbai',
      city: 'Mumbai',
      country: 'IN',
      category: 'Artisan Cafe & Roastery',
      tags: ['Cafe', 'Single Origin Coffee', 'Breakfast', 'Work-Friendly'],
      lat: 18.9287,
      lng: 72.8331,
      ownerId: null,
      createdAt: now(90),
      updatedAt: now(2),
    },
    {
      id: 'store_mum_004',
      name: 'Britannia & Co. Heritage Restaurant',
      email: 'contact@britanniamumbai.com',
      address: 'Wakefield House, 11 Sprott Road, Ballard Estate, Fort, Mumbai',
      city: 'Mumbai',
      country: 'IN',
      category: 'Heritage Parsi & Irani Cafe',
      tags: ['Restaurant', 'Heritage', 'Berry Pulao', 'Lunch'],
      lat: 18.9351,
      lng: 72.8402,
      ownerId: null,
      createdAt: now(85),
      updatedAt: now(5),
    },
    {
      id: 'store_mum_005',
      name: 'Candies at Mac Ronells',
      email: 'hello@candiesbandra.com',
      address: '5AA Pali Hill, Next to Learners Academy, Bandra West, Mumbai',
      city: 'Mumbai',
      country: 'IN',
      category: 'Vintage Garden Cafe & Bakery',
      tags: ['Cafe', 'Bakery', 'Garden Seating', 'Casual Dining'],
      lat: 19.0628,
      lng: 72.8290,
      ownerId: null,
      createdAt: now(80),
      updatedAt: now(6),
    },
    {
      id: 'store_mum_006',
      name: 'Bastian Seafood & Grill',
      email: 'reservations@bastianmumbai.com',
      address: 'B/1 New Kamal Building, Linking Road, Bandra West, Mumbai',
      city: 'Mumbai',
      country: 'IN',
      category: 'Seafood Restaurant & Brunch',
      tags: ['Restaurant', 'Seafood', 'Brunch', 'Cheesecakes'],
      lat: 19.0601,
      lng: 72.8360,
      ownerId: null,
      createdAt: now(75),
      updatedAt: now(8),
    },

    // --- DELHI NCR Cafes & Restaurants ---
    {
      id: 'store_del_001',
      name: 'Indian Accent',
      email: 'reservations@indianaccent.com',
      address: 'The Lodhi, Lodhi Road, New Delhi',
      city: 'Delhi',
      country: 'IN',
      category: 'Contemporary Fine Dining',
      tags: ['Restaurant', 'Fine Dining', 'Modern Indian', 'Tasting Menu'],
      lat: 28.5919,
      lng: 77.2374,
      ownerId: null,
      createdAt: now(110),
      updatedAt: now(2),
    },
    {
      id: 'store_del_002',
      name: 'Cafe Lota',
      email: 'namaste@cafelota.in',
      address: 'National Crafts Museum, Bhairon Marg, Pragati Maidan, New Delhi',
      city: 'Delhi',
      country: 'IN',
      category: 'Regional Indian Artisan Cafe',
      tags: ['Cafe', 'Regional Indian', 'Open Air', 'Filter Coffee'],
      lat: 28.6145,
      lng: 77.2427,
      ownerId: null,
      createdAt: now(105),
      updatedAt: now(1),
    },
    {
      id: 'store_del_003',
      name: 'Perch Wine & Coffee Bar',
      email: 'khanmarket@perch.in',
      address: '71, 1st & 2nd Floor, Khan Market, Rabindra Nagar, New Delhi',
      city: 'Delhi',
      country: 'IN',
      category: 'Wine Bar & Specialty Coffee Cafe',
      tags: ['Cafe', 'Wine Bar', 'Coffee', 'European Bistro'],
      lat: 28.6003,
      lng: 77.2272,
      ownerId: null,
      createdAt: now(98),
      updatedAt: now(3),
    },
    {
      id: 'store_del_004',
      name: 'Diggin Garden Cafe',
      email: 'anandlok@diggincafe.com',
      address: 'No. 1 & 2 Anand Lok Shopping Centre, Opposite Gargi College, New Delhi',
      city: 'Delhi',
      country: 'IN',
      category: 'Italian Garden Cafe & Trattoria',
      tags: ['Cafe', 'Italian', 'Wood-fired Pizza', 'Patio'],
      lat: 28.5558,
      lng: 77.2185,
      ownerId: null,
      createdAt: now(92),
      updatedAt: now(4),
    },

    // --- BENGALURU Cafes & Restaurants ---
    {
      id: 'store_blr_001',
      name: 'Third Wave Coffee Roasters (Koramangala)',
      email: 'koramangala@thirdwavecoffee.in',
      address: '984, 80 Feet Road, 4th Block, Koramangala, Bengaluru',
      city: 'Bengaluru',
      country: 'IN',
      category: 'Specialty Coffee Roastery & Cafe',
      tags: ['Cafe', 'Pour Over', 'Specialty Coffee', 'Work-Friendly'],
      lat: 12.9345,
      lng: 77.6266,
      ownerId: 'usr_owner_002',
      createdAt: now(112),
      updatedAt: now(1),
    },
    {
      id: 'store_blr_002',
      name: 'Vidyarthi Bhavan',
      email: 'info@vidyarthibhavan.in',
      address: '32 Gandhi Bazaar Main Road, Basavanagudi, Bengaluru',
      city: 'Bengaluru',
      country: 'IN',
      category: 'Heritage South Indian Eatery',
      tags: ['Restaurant', 'Heritage', 'Crispy Dosa', 'Filter Coffee'],
      lat: 12.9438,
      lng: 77.5714,
      ownerId: null,
      createdAt: now(115),
      updatedAt: now(2),
    },
    {
      id: 'store_blr_003',
      name: 'Toit Brewpub & Kitchen',
      email: 'indiranagar@toitbrewing.com',
      address: '298, 100 Feet Road, Near KFC Signal, Indiranagar, Bengaluru',
      city: 'Bengaluru',
      country: 'IN',
      category: 'Craft Microbrewery & Gastropub',
      tags: ['Restaurant', 'Brewpub', 'Craft Beer', 'Woodfired Pizza'],
      lat: 12.9793,
      lng: 77.6406,
      ownerId: null,
      createdAt: now(108),
      updatedAt: now(3),
    },
    {
      id: 'store_blr_004',
      name: 'Araku Coffee Flagship',
      email: 'indiranagar@arakucoffee.com',
      address: '968, 12th Main Road, HAL 2nd Stage, Indiranagar, Bengaluru',
      city: 'Bengaluru',
      country: 'IN',
      category: 'Luxury Single-Origin Coffee Boutique',
      tags: ['Cafe', 'Artisan Coffee', 'Patisserie', 'Organic'],
      lat: 12.9718,
      lng: 77.6412,
      ownerId: null,
      createdAt: now(94),
      updatedAt: now(2),
    },

    // --- PUNE Cafes & Restaurants ---
    {
      id: 'store_pun_001',
      name: 'Cafe Goodluck',
      email: 'fc@cafegoodluck.in',
      address: 'Goodluck Chowk, Deccan Gymkhana, FC Road, Pune',
      city: 'Pune',
      country: 'IN',
      category: 'Historic Irani Cafe & Breakfast',
      tags: ['Cafe', 'Bun Maska', 'Irani Chai', 'Iconic Breakfast'],
      lat: 18.5167,
      lng: 73.8415,
      ownerId: null,
      createdAt: now(120),
      updatedAt: now(1),
    },
    {
      id: 'store_pun_002',
      name: 'German Bakery',
      email: 'kp@germanbakerypune.com',
      address: '292 North Main Road, Ragvilas Society, Koregaon Park, Pune',
      city: 'Pune',
      country: 'IN',
      category: 'Organic Bakery Cafe & Eatery',
      tags: ['Cafe', 'Bakery', 'Organic', 'Outdoor Seating'],
      lat: 18.5362,
      lng: 73.8940,
      ownerId: null,
      createdAt: now(110),
      updatedAt: now(3),
    },

    // --- HYDERABAD Cafes & Restaurants ---
    {
      id: 'store_hyd_001',
      name: 'Roastery Coffee House',
      email: 'banjarahills@roasterycoffee.com',
      address: 'House 418, Road No. 14, Banjara Hills, Hyderabad',
      city: 'Hyderabad',
      country: 'IN',
      category: 'Artisan Coffee Roastery & Garden Cafe',
      tags: ['Cafe', 'Specialty Roaster', 'Garden Cafe', 'Cold Brew'],
      lat: 17.4168,
      lng: 78.4385,
      ownerId: null,
      createdAt: now(98),
      updatedAt: now(2),
    },
    {
      id: 'store_hyd_003',
      name: 'Paradise Heritage Restaurant',
      email: 'guest@paradisebiryani.in',
      address: 'Sappu Bagh Commercial Complex, MG Road, Secunderabad, Hyderabad',
      city: 'Hyderabad',
      country: 'IN',
      category: 'Legendary Hyderabadi Restaurant',
      tags: ['Restaurant', 'Dum Biryani', 'Kebabs', 'Heritage'],
      lat: 17.4416,
      lng: 78.4983,
      ownerId: null,
      createdAt: now(118),
      updatedAt: now(3),
    },

    // --- JAIPUR Cafes & Restaurants ---
    {
      id: 'store_jai_001',
      name: 'Tapri Central Rooftop Cafe',
      email: 'chai@tapri.net',
      address: 'B4-E, Prithviraj Road, Opposite Central Park, C-Scheme, Jaipur',
      city: 'Jaipur',
      country: 'IN',
      category: 'Artisanal Tea House & Rooftop Cafe',
      tags: ['Cafe', 'Chai Bar', 'Rooftop View', 'Indian Street Food'],
      lat: 26.9067,
      lng: 75.8083,
      ownerId: null,
      createdAt: now(96),
      updatedAt: now(3),
    },
    {
      id: 'store_jai_002',
      name: 'Anokhi Cafe',
      email: 'cafe@anokhijaipur.com',
      address: 'KK Square, 2nd Floor, C-11 Prithviraj Road, C-Scheme, Jaipur',
      city: 'Jaipur',
      country: 'IN',
      category: 'Organic Farm-to-Table Cafe',
      tags: ['Cafe', 'Organic', 'Salad Bar', 'Fresh Bakes'],
      lat: 26.9032,
      lng: 75.8041,
      ownerId: null,
      createdAt: now(91),
      updatedAt: now(5),
    },

    // --- KOLKATA Cafes & Restaurants ---
    {
      id: 'store_kol_001',
      name: 'Flurys Tearoom & Confectionery',
      email: 'parkstreet@flurys.com',
      address: '18 Park Street, Taltala, Kolkata',
      city: 'Kolkata',
      country: 'IN',
      category: 'Heritage Tearoom & European Bakery',
      tags: ['Cafe', 'Heritage Tearoom', 'English Breakfast', 'Pastries'],
      lat: 22.5518,
      lng: 88.3524,
      ownerId: null,
      createdAt: now(125),
      updatedAt: now(2),
    },
    {
      id: 'store_kol_002',
      name: 'Peter Cat',
      email: 'service@petercatkolkata.com',
      address: '18A Park Street, Stephen Court, Kolkata',
      city: 'Kolkata',
      country: 'IN',
      category: 'Iconic Continental & Indian Dining',
      tags: ['Restaurant', 'Chelo Kebab', 'Continental', 'Cocktails'],
      lat: 22.5521,
      lng: 88.3529,
      ownerId: null,
      createdAt: now(120),
      updatedAt: now(4),
    },

    // --- CHENNAI Cafes & Restaurants ---
    {
      id: 'store_chn_001',
      name: 'Amethyst Wild Garden Cafe',
      email: 'wildgarden@amethystchennai.com',
      address: 'Entrance on Whites Road, Royapettah, Chennai',
      city: 'Chennai',
      country: 'IN',
      category: 'Colonial Garden Cafe & Bistro',
      tags: ['Cafe', 'Garden Seating', 'European Bistro', 'Specialty Coffee'],
      lat: 13.0538,
      lng: 80.2599,
      ownerId: null,
      createdAt: now(104),
      updatedAt: now(2),
    },
    {
      id: 'store_chn_002',
      name: 'Murugan Idli Shop',
      email: 'contact@muruganidlishop.com',
      address: '46/1 GN Chetty Road, T. Nagar, Chennai',
      city: 'Chennai',
      country: 'IN',
      category: 'Traditional South Indian Dining',
      tags: ['Restaurant', 'Steamed Idli', 'Filter Coffee', 'Traditional'],
      lat: 13.0418,
      lng: 80.2337,
      ownerId: null,
      createdAt: now(115),
      updatedAt: now(3),
    },

    // Legacy test stores (retained for backward compatibility and test 3)
    {
      id: 'store_001',
      name: 'Field & Finch',
      email: 'hello@fieldandfinch.com',
      address: '82 Alder Street, Portland, OR',
      city: 'Portland',
      country: 'US',
      category: 'Boutique & Pantry',
      tags: ['Boutique', 'Coffee', 'Pantry'],
      lat: 45.5152,
      lng: -122.6784,
      ownerId: 'usr_owner_001',
      createdAt: now(84),
      updatedAt: now(5),
    },
    {
      id: 'store_002',
      name: 'Northline Books',
      email: 'hello@northlinebooks.com',
      address: '5 Market Lane, Austin, TX',
      city: 'Austin',
      country: 'US',
      category: 'Bookshop Cafe',
      tags: ['Books', 'Cafe', 'Reading Room'],
      lat: 30.2672,
      lng: -97.7431,
      ownerId: 'usr_owner_002',
      createdAt: now(76),
      updatedAt: now(4),
    },
    {
      id: 'store_003',
      name: 'Morrow Coffee Lab',
      email: 'hello@morrowcoffee.com',
      address: '211 Cedar Street, Seattle, WA',
      city: 'Seattle',
      country: 'US',
      category: 'Artisan Coffee Roastery',
      tags: ['Coffee', 'Cafe', 'Espresso Lab'],
      lat: 47.6062,
      lng: -122.3321,
      ownerId: null,
      createdAt: now(63),
      updatedAt: now(13),
    },
    {
      id: 'store_004',
      name: 'Common Thread Market',
      email: 'hello@commonthread.market',
      address: '18 Olive Avenue, Brooklyn, NY',
      city: 'New York',
      country: 'US',
      category: 'Artisan Grocer & Cafe',
      tags: ['Grocer', 'Cafe', 'Deli'],
      lat: 40.6782,
      lng: -73.9442,
      ownerId: null,
      createdAt: now(41),
      updatedAt: now(11),
    },
    {
      id: 'store_005',
      name: 'Signal House Plants',
      email: 'hello@signalhouseplants.com',
      address: '73 Willow Road, Los Angeles, CA',
      city: 'Los Angeles',
      country: 'US',
      category: 'Botanical Cafe & Plants',
      tags: ['Plants', 'Cafe', 'Greenhouse'],
      lat: 34.0522,
      lng: -118.2437,
      ownerId: null,
      createdAt: now(28),
      updatedAt: now(9),
    },
  ];

  db.ratings = [
    { id: 'rating_001', userId: 'usr_user_001', storeId: 'store_001', rating: 5, createdAt: now(12), updatedAt: now(12) },
    { id: 'rating_002', userId: 'usr_user_002', storeId: 'store_001', rating: 4, createdAt: now(8), updatedAt: now(8) },
    { id: 'rating_003', userId: 'usr_user_003', storeId: 'store_001', rating: 5, createdAt: now(3), updatedAt: now(3) },
    { id: 'rating_004', userId: 'usr_user_001', storeId: 'store_002', rating: 4, createdAt: now(16), updatedAt: now(16) },
    { id: 'rating_005', userId: 'usr_user_002', storeId: 'store_002', rating: 3, createdAt: now(6), updatedAt: now(6) },
    { id: 'rating_006', userId: 'usr_user_003', storeId: 'store_003', rating: 5, createdAt: now(4), updatedAt: now(4) },
    { id: 'rating_007', userId: 'usr_user_002', storeId: 'store_004', rating: 4, createdAt: now(9), updatedAt: now(9) },

    // BHOPAL ratings
    { id: 'rating_bho_01', userId: 'usr_user_001', storeId: 'store_bho_001', rating: 5, createdAt: now(3), updatedAt: now(3) },
    { id: 'rating_bho_02', userId: 'usr_user_002', storeId: 'store_bho_001', rating: 5, createdAt: now(2), updatedAt: now(2) },
    { id: 'rating_bho_03', userId: 'usr_user_001', storeId: 'store_bho_002', rating: 5, createdAt: now(4), updatedAt: now(4) },
    { id: 'rating_bho_04', userId: 'usr_user_003', storeId: 'store_bho_002', rating: 5, createdAt: now(1), updatedAt: now(1) },
    { id: 'rating_bho_05', userId: 'usr_user_001', storeId: 'store_bho_003', rating: 5, createdAt: now(5), updatedAt: now(5) },
    { id: 'rating_bho_06', userId: 'usr_user_002', storeId: 'store_bho_004', rating: 5, createdAt: now(8), updatedAt: now(8) },
    { id: 'rating_bho_07', userId: 'usr_user_001', storeId: 'store_bho_005', rating: 5, createdAt: now(6), updatedAt: now(6) },
    { id: 'rating_bho_08', userId: 'usr_user_003', storeId: 'store_bho_006', rating: 5, createdAt: now(7), updatedAt: now(7) },
    { id: 'rating_bho_09', userId: 'usr_user_001', storeId: 'store_bho_007', rating: 4, createdAt: now(9), updatedAt: now(9) },
    { id: 'rating_bho_10', userId: 'usr_user_002', storeId: 'store_bho_008', rating: 5, createdAt: now(2), updatedAt: now(2) },
    { id: 'rating_bho_11', userId: 'usr_user_001', storeId: 'store_bho_009', rating: 5, createdAt: now(10), updatedAt: now(10) },
    { id: 'rating_bho_12', userId: 'usr_user_003', storeId: 'store_bho_010', rating: 5, createdAt: now(4), updatedAt: now(4) },

    // INDORE ratings
    { id: 'rating_ind_01', userId: 'usr_user_001', storeId: 'store_ind_001', rating: 5, createdAt: now(3), updatedAt: now(3) },
    { id: 'rating_ind_02', userId: 'usr_user_002', storeId: 'store_ind_002', rating: 5, createdAt: now(4), updatedAt: now(4) },
    { id: 'rating_ind_03', userId: 'usr_user_003', storeId: 'store_ind_003', rating: 4, createdAt: now(5), updatedAt: now(5) },

    // MUMBAI ratings
    { id: 'rating_mum_01', userId: 'usr_user_001', storeId: 'store_mum_001', rating: 5, createdAt: now(5), updatedAt: now(5) },
    { id: 'rating_mum_02', userId: 'usr_user_002', storeId: 'store_mum_001', rating: 5, createdAt: now(4), updatedAt: now(4) },
    { id: 'rating_mum_03', userId: 'usr_user_003', storeId: 'store_mum_001', rating: 5, createdAt: now(2), updatedAt: now(2) },
    { id: 'rating_mum_04', userId: 'usr_user_001', storeId: 'store_mum_002', rating: 5, createdAt: now(6), updatedAt: now(6) },
    { id: 'rating_mum_05', userId: 'usr_user_002', storeId: 'store_mum_002', rating: 4, createdAt: now(5), updatedAt: now(5) },
    { id: 'rating_mum_06', userId: 'usr_user_001', storeId: 'store_mum_003', rating: 5, createdAt: now(7), updatedAt: now(7) },
    { id: 'rating_mum_07', userId: 'usr_user_003', storeId: 'store_mum_005', rating: 4, createdAt: now(8), updatedAt: now(8) },

    // DELHI ratings
    { id: 'rating_del_01', userId: 'usr_user_002', storeId: 'store_del_001', rating: 5, createdAt: now(5), updatedAt: now(5) },
    { id: 'rating_del_02', userId: 'usr_user_001', storeId: 'store_del_001', rating: 5, createdAt: now(3), updatedAt: now(3) },
    { id: 'rating_del_03', userId: 'usr_user_002', storeId: 'store_del_002', rating: 5, createdAt: now(4), updatedAt: now(4) },
    { id: 'rating_del_04', userId: 'usr_user_003', storeId: 'store_del_003', rating: 4, createdAt: now(6), updatedAt: now(6) },
    { id: 'rating_del_05', userId: 'usr_user_002', storeId: 'store_del_004', rating: 5, createdAt: now(7), updatedAt: now(7) },

    // BENGALURU ratings
    { id: 'rating_blr_01', userId: 'usr_user_003', storeId: 'store_blr_001', rating: 5, createdAt: now(2), updatedAt: now(2) },
    { id: 'rating_blr_02', userId: 'usr_user_001', storeId: 'store_blr_001', rating: 5, createdAt: now(1), updatedAt: now(1) },
    { id: 'rating_blr_03', userId: 'usr_user_003', storeId: 'store_blr_002', rating: 5, createdAt: now(8), updatedAt: now(8) },
    { id: 'rating_blr_04', userId: 'usr_user_002', storeId: 'store_blr_003', rating: 5, createdAt: now(4), updatedAt: now(4) },
    { id: 'rating_blr_05', userId: 'usr_user_003', storeId: 'store_blr_004', rating: 5, createdAt: now(3), updatedAt: now(3) },

    // PUNE ratings
    { id: 'rating_pun_01', userId: 'usr_user_001', storeId: 'store_pun_001', rating: 5, createdAt: now(6), updatedAt: now(6) },
    { id: 'rating_pun_02', userId: 'usr_user_002', storeId: 'store_pun_002', rating: 4, createdAt: now(5), updatedAt: now(5) },

    // HYDERABAD ratings
    { id: 'rating_hyd_01', userId: 'usr_user_003', storeId: 'store_hyd_001', rating: 5, createdAt: now(7), updatedAt: now(7) },
    { id: 'rating_hyd_02', userId: 'usr_user_002', storeId: 'store_hyd_003', rating: 5, createdAt: now(9), updatedAt: now(9) },

    // JAIPUR ratings
    { id: 'rating_jai_01', userId: 'usr_user_002', storeId: 'store_jai_001', rating: 5, createdAt: now(4), updatedAt: now(4) },
    { id: 'rating_jai_02', userId: 'usr_user_001', storeId: 'store_jai_002', rating: 4, createdAt: now(7), updatedAt: now(7) },

    // KOLKATA ratings
    { id: 'rating_kol_01', userId: 'usr_user_001', storeId: 'store_kol_001', rating: 5, createdAt: now(11), updatedAt: now(11) },
    { id: 'rating_kol_02', userId: 'usr_user_002', storeId: 'store_kol_002', rating: 5, createdAt: now(10), updatedAt: now(10) },

    // CHENNAI ratings
    { id: 'rating_chn_01', userId: 'usr_user_003', storeId: 'store_chn_001', rating: 5, createdAt: now(6), updatedAt: now(6) },
    { id: 'rating_chn_02', userId: 'usr_user_001', storeId: 'store_chn_002', rating: 5, createdAt: now(8), updatedAt: now(8) },
  ];
  saveDbToFile();
};

export const getUser = (id) => {
  let user = db.users.find((u) => u.id === id);
  if (!user && loadDbFromFile()) {
    user = db.users.find((u) => u.id === id);
  }
  return user;
};
export const getStore = (id) => db.stores.find((store) => store.id === id);
export const getRating = (userId, storeId) => db.ratings.find((rating) => rating.userId === userId && rating.storeId === storeId);

export const publicUser = (user) => ({
  id: user.id,
  name: user.name,
  email: user.email,
  address: user.address,
  city: user.city || null,
  lat: user.lat ?? null,
  lng: user.lng ?? null,
  role: user.role,
  createdAt: user.createdAt,
  updatedAt: user.updatedAt,
});

export const averageForStore = (storeId) => {
  const ratings = db.ratings.filter((rating) => rating.storeId === storeId);
  if (!ratings.length) return null;
  return Math.round((ratings.reduce((sum, rating) => sum + rating.rating, 0) / ratings.length) * 10) / 10;
};

export const countForStore = (storeId) => db.ratings.filter((rating) => rating.storeId === storeId).length;

resetData(false);

